CREATE DATABASE QUANLYQUANPHUCLONG;



USE QUANLYQUANPHUCLONG;

/****** Object:  Table BAN    Script Date: 8/29/2022 8:30:17 PM ******/

CREATE TABLE BAN(
	ID bigint AUTO_INCREMENT NOT NULL,
	SOGHE int NOT NULL,
	LOAI bigint NOT NULL,
	TINHTRANG int NOT NULL,
 CONSTRAINT PK__BAN__3214EC27365E0C5E PRIMARY KEY CLUSTERED 
(
	ID ASC
)
);


/****** Object:  Table CHIPHI    Script Date: 8/29/2022 8:30:17 PM ******/
   
CREATE TABLE CHIPHI(
	ID bigint AUTO_INCREMENT NOT NULL,
	TENNL nvarchar(50) NOT NULL,
	SOLUONG int NOT NULL,
	NGAYNHAP date NOT NULL,
	GIAMOIDV int NOT NULL,
	LOAI nvarchar(3) NOT NULL,
	DV nvarchar(10) NULL,
	NHACUNGCAP nvarchar(50) NULL,
	GHICHU nvarchar(50) NULL,
	NVTAO bigint NULL,
 CONSTRAINT PK_CHIPHI PRIMARY KEY CLUSTERED 
(
	ID ASC
));


/****** Object:  Table CHITIETHD    Script Date: 8/29/2022 8:30:17 PM ******/
   


CREATE TABLE CHITIETHD(
	MAHD bigint NOT NULL,
	MASP varchar(10) NOT NULL,
	SOLUONG int NOT NULL,
	TONGTIEN int NOT NULL,
 CONSTRAINT PK PRIMARY KEY CLUSTERED 
(
	MAHD ASC,
	MASP ASC
),
 CONSTRAINT UQ__CHITIETH__563D086C67A0DCB1 UNIQUE NONCLUSTERED 
(
	MAHD ASC,
	MASP ASC
));




/****** Object:  Table CHUCVU    Script Date: 8/29/2022 8:30:17 PM ******/
   
CREATE TABLE CHUCVU(
	ID bigint AUTO_INCREMENT NOT NULL,
	TENCHUCVU nvarchar(30) NOT NULL,
 CONSTRAINT PK__CHUCVU__006568E958DDDE19 PRIMARY KEY CLUSTERED 
(
	ID ASC
));


/****** Object:  Table DATBAN    Script Date: 8/29/2022 8:30:17 PM ******/
   


CREATE TABLE DATBAN(
	ID bigint AUTO_INCREMENT NOT NULL,
	HOTEN nvarchar(50) NOT NULL,
	SDT varchar(10) NOT NULL,
	TIENCOC int NOT NULL,
	NGAYDAT date NOT NULL,
	TGDUKIEN datetime NOT NULL,
	NVTHUCHIEN bigint NOT NULL,
	TRANGTHAI int NOT NULL,
	BAN bigint NOT NULL,
 CONSTRAINT PK__DATBAN__77CD11CE46986D6C PRIMARY KEY CLUSTERED 
(
	ID ASC
));



/****** Object:  Table HOADON    Script Date: 8/29/2022 8:30:17 PM ******/
   
CREATE TABLE HOADON(
	ID bigint AUTO_INCREMENT NOT NULL,
	NGAYTHUCHIEN datetime NOT NULL,
	BAN bigint NOT NULL,
	NVTHUCHIEN bigint NULL,
	TINHTRANG int NOT NULL,
 CONSTRAINT PK__HOADON__603F20CEFBED6B49 PRIMARY KEY CLUSTERED 
(
	ID ASC
));


/****** Object:  Table LOAIBAN    Script Date: 8/29/2022 8:30:17 PM ******/
   
CREATE TABLE LOAIBAN(
	ID bigint AUTO_INCREMENT NOT NULL,
	TENLOAI nvarchar(20) NOT NULL,
	GIADAT int NOT NULL,
 CONSTRAINT PK_LOAIBAN PRIMARY KEY CLUSTERED 
(
	ID ASC
));


/****** Object:  Table LOAITHUCUONG    Script Date: 8/29/2022 8:30:17 PM ******/
   


CREATE TABLE LOAITHUCUONG(
	ID varchar(10) NOT NULL,
	TENLOAI nvarchar(50) NOT NULL,
	DONVI nvarchar(10) NOT NULL,
 CONSTRAINT PK__LOAITHUC__3214EC27EE943000 PRIMARY KEY CLUSTERED 
(
	ID ASC
));



/****** Object:  Table NHANVIEN    Script Date: 8/29/2022 8:30:17 PM ******/
   


CREATE TABLE NHANVIEN(
	MANV bigint AUTO_INCREMENT NOT NULL,
	HOTEN nvarchar(50) NOT NULL,
	NGAYSINH date NOT NULL,
	GIOITINH bit NOT NULL,
	LUONG int NOT NULL,
	SDT varchar(10) NOT NULL,
	CMND varchar(15) NOT NULL,
	DIACHI nvarchar(50) NULL,
	NGAYVAOLAM date NOT NULL,
	DANGHI bit NOT NULL,
 CONSTRAINT PK__NHANVIEN__603F5114708D8A0A PRIMARY KEY CLUSTERED 
(
	MANV ASC
));


/****** Object:  Table THUCDON    Script Date: 8/29/2022 8:30:17 PM ******/
   

CREATE TABLE THUCDON(
	ID varchar(10) NOT NULL,
	TEN nvarchar(50) NOT NULL,
	LOAI varchar(10) NOT NULL,
	GIA int NOT NULL,
 CONSTRAINT PK__THUCDON__3214EC27AEAED7EA PRIMARY KEY CLUSTERED 
(
	ID ASC
));



/****** Object:  Table USERTB    Script Date: 8/29/2022 8:30:17 PM ******/

CREATE TABLE USERTB(
	USERNAME varchar(20) NOT NULL,
	PASSWD varchar(50) NOT NULL,
	ID bigint NOT NULL,
	ROLEID bigint NOT NULL,
	STATUS int NOT NULL,
	EMAIL nvarchar(50) NOT NULL,
	ICON nvarchar(50) NOT NULL
 );



ALTER TABLE BAN alter TINHTRANG SET DEFAULT 0;
-- ALTER TABLE BAN ADD  CONSTRAINT DF_BAN_TINHTRANG  DEFAULT ((0)) FOR TINHTRANG

ALTER TABLE CHITIETHD alter TONGTIEN SET DEFAULT 0;
-- ALTER TABLE CHITIETHD ADD  CONSTRAINT DF_CHITIETHD_TONGTIEN  DEFAULT ((0)) FOR TONGTIEN

ALTER TABLE DATBAN alter TRANGTHAI SET DEFAULT 0;
-- ALTER TABLE DATBAN ADD  CONSTRAINT DF_DATBAN_TRANGTHAI  DEFAULT ((0)) FOR TRANGTHAI

ALTER TABLE HOADON alter NGAYTHUCHIEN SET DEFAULT (CURRENT_DATE());
-- ALTER TABLE HOADON ADD  CONSTRAINT DF__HOADON__NGAYTHUC__1FCDBCEB  DEFAULT (getdate()) FOR NGAYTHUCHIEN

ALTER TABLE HOADON alter BAN SET DEFAULT 1;
-- ALTER TABLE HOADON ADD  CONSTRAINT DF_HOADON_BAN  DEFAULT ((1)) FOR BAN

ALTER TABLE HOADON alter TINHTRANG SET DEFAULT 0;
-- ALTER TABLE HOADON ADD  CONSTRAINT DF_HOADON_TINHTRANG  DEFAULT ((0)) FOR TINHTRANG

ALTER TABLE NHANVIEN alter GIOITINH SET DEFAULT 1;
-- ALTER TABLE NHANVIEN ADD  CONSTRAINT DF_NHANVIEN_GIOITINH  DEFAULT ((1)) FOR GIOITINH

ALTER TABLE NHANVIEN alter NGAYVAOLAM SET DEFAULT (CURRENT_DATE());
-- ALTER TABLE NHANVIEN ADD  CONSTRAINT DF__NHANVIEN__NGAYVA__267ABA7A  DEFAULT (getdate()) FOR NGAYVAOLAM

ALTER TABLE NHANVIEN alter DANGHI SET DEFAULT 0;
-- ALTER TABLE NHANVIEN ADD  CONSTRAINT DF_NHANVIEN_DANGHI  DEFAULT ((0)) FOR DANGHI

ALTER TABLE USERTB alter EMAIL SET DEFAULT (N'n19dccn000@studen.ptithcm.edu.vn');
-- ALTER TABLE USERTB ADD  CONSTRAINT DF_USERTB_EMAIL  DEFAULT (N'n19dccn000@studen.ptithcm.edu.vn') FOR EMAIL

ALTER TABLE USERTB alter ICON SET DEFAULT  (N'lo_highland.png');
-- ALTER TABLE USERTB ADD  CONSTRAINT DF_USERTB_ICON  DEFAULT (N'lo_highland.png') FOR ICON




ALTER TABLE BAN   ADD  CONSTRAINT FK_BAN_LOAIBAN FOREIGN KEY(LOAI)
REFERENCES LOAIBAN (ID)
ON UPDATE CASCADE;



ALTER TABLE CHIPHI   ADD  CONSTRAINT FK_CHIPHI_NHANVIEN FOREIGN KEY(NVTAO)
REFERENCES NHANVIEN (MANV);



ALTER TABLE CHITIETHD   ADD  CONSTRAINT FK_CHITIETHD_HOADON FOREIGN KEY(MAHD)
REFERENCES HOADON (ID);



ALTER TABLE CHITIETHD   ADD  CONSTRAINT FK_CHITIETHD_THUCDON FOREIGN KEY(MASP)
REFERENCES THUCDON (ID)
ON UPDATE CASCADE;



ALTER TABLE DATBAN   ADD  CONSTRAINT FK_DATBAN_BAN FOREIGN KEY(BAN)
REFERENCES BAN (ID);



ALTER TABLE DATBAN   ADD  CONSTRAINT FK_DATBAN_NHANVIEN FOREIGN KEY(NVTHUCHIEN)
REFERENCES NHANVIEN (MANV)

;

ALTER TABLE HOADON   ADD  CONSTRAINT FK_HOADON_BAN FOREIGN KEY(BAN)
REFERENCES BAN (ID)

;

ALTER TABLE HOADON   ADD  CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(NVTHUCHIEN)
REFERENCES NHANVIEN (MANV)

;

ALTER TABLE THUCDON   ADD  CONSTRAINT FK_THUCDON_LOAITHUCUONG FOREIGN KEY(LOAI)
REFERENCES LOAITHUCUONG (ID)

;

ALTER TABLE USERTB   ADD  CONSTRAINT FK_USERTB_CHUCVU FOREIGN KEY(ROLEID)
REFERENCES CHUCVU (ID)
ON UPDATE CASCADE

;

ALTER TABLE USERTB   ADD  CONSTRAINT FK_USERTB_NHANVIEN FOREIGN KEY(ID)
REFERENCES NHANVIEN (MANV)

;

ALTER TABLE CHIPHI   ADD  CONSTRAINT CK__CHIPHI__SOLUONG__607251E5 CHECK  ((soluong>(0)))

;



